WFH-240/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WFH_240.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

WFH-240/Controllers/PelamarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WFH_240.Controllers
{
    public class PelamarController : Controller
    {
        // GET: Pelamar
        public ActionResult Index()
        {
            return View();
        }

    }
}

WFH-240/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

WFH-240/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

WFH-240/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<h1 style="background-color:white;font-weight:bold; color:#000066;">
    XSIS 2.0
</h1>
<div class="navSide" style="background-color: transparent">
    <aside class="main-sidebar" style="color:#000066">
        <section class="sidebar col-sm-3" style="color:#ffffff; padding:0px 15px 0px 15px">
            <br /> <!--table-bordered-->
            <div class="list-group list-group-flush" style="border:2px solid #000066">
                <a href="@Url.Action("Index", "Home")" class="list-group-item list-group-item-action bg-light" style="border-bottom:3px solid #000066; color:darkblue"><i class="glyphicon glyphicon-adjust"></i><b> &nbsp; Beranda</b></a>
                <a href="@Url.Action("Index", "Pelamar")" class="list-group-item list-group-item-action bg-light" style="border-bottom:3px solid #000066; color:darkblue"><i class="glyphicon glyphicon-adjust"></i><b> &nbsp; Pelamar</b></a>
                <a href="#" class="list-group-item list-group-item-action bg-act" style="border-bottom:3px solid #000066; color:darkblue"><i class="glyphicon glyphicon-adjust"></i><b> &nbsp; Proses Pelamar</b></a>
                <ul class="list-group-item list-group-item-action bg-light">
                    <li class="dropdown notifications-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <span class="logo-lg"><b>Penjadwalan</b></span>
                            <i class="glyphicon glyphicon-chevron-down"></i>
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            <li><a class="list-group-item list-group-item-action" href="#">Rencana</a></li>
                            <li><a class="list-group-item list-group-item-action" href="@Url.Action("Index", "Undangan")">Undangan</a></li>
                        </ul>
                    </li>
                </ul>
                <ul class="list-group-item list-group-item-action bg-light">
                    <li class="dropdown notifications-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <span class="logo-lg"><b>Penjadwalan Ulang</b></span>
                            <i class="glyphicon glyphicon-chevron-down"></i>
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            <li><a class="list-group-item list-group-item-action" href="@Url.Action("Index", "RescheduleUndangan")">Undangan</a></li>
                        </ul>
                    </li>
                </ul>
                <a href="#" class="list-group-item list-group-item-action bg-light" style="border-bottom:3px solid #000066; color:darkblue"><i class="glyphicon glyphicon-adjust"></i><b> &nbsp; Tes</b></a>
                <a href="#" class="list-group-item list-group-item-action bg-light" style="border-bottom:3px solid #000066; color:darkblue"><i class="glyphicon glyphicon-adjust"></i><b> &nbsp; Bootcamp</b></a>
                <a href="#" class="list-group-item list-group-item-action bg-light" style="border-bottom:3px solid #000066; color:darkblue"><i class="glyphicon glyphicon-adjust"></i><b> &nbsp; Laporan</b></a>
                <ul class="list-group-item list-group-item-action bg-light">
                    <li class="dropdown notifications-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <span class="logo-lg"><b>Time Report</b></span>
                            <i class="glyphicon glyphicon-chevron-down"></i>
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            <li><a class="list-group-item list-group-item-action" href="#">Timesheet</a></li>
                            <li><a class="list-group-item list-group-item-action" href="#" id="btn-tsa">Timesheet Approval</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </section>
    </aside>
</div>

<div class="container body-content" style="background:white">
    <br/>

</div>