WFH-240/Controllers/PermissionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WFHDataModel;
using WFHRepository;
using WFHViewModel;

namespace WFH_240.Controllers
{
    public class PermissionController : Controller
    {
        // GET: Permission
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult HistoryList(int pageHis = 1, bool sortAscHis = true, int perPageHis = 10)
        {
            Pagination pg = PermissionRepo.PagingHis(pageHis, sortAscHis, perPageHis);
            ViewBag.currPageHis = pageHis;
            ViewBag.PageCountHis = pg.Pages;
            return PartialView("_HistoryList", pg.ListOf);
        }
        public ActionResult SearchHis(DateTime datefrom, DateTime dateto)
        {
            ViewBag.PageOf = 1;
            return PartialView("_HistoryList", PermissionRepo.DateSearchHis(datefrom, dateto));
        }

        public ActionResult ApprovalList(int pageApp = 1, bool sortAscApp = true, int perPageApp = 10)
        {
            Pagination pg = PermissionRepo.PagingApp(pageApp, sortAscApp, perPageApp);
            ViewBag.currPageApp = pageApp;
            ViewBag.PageCountApp = pg.Pages;
            return PartialView("_ApprovalList", pg.ListOf);
        }
        public ActionResult SearchApp(DateTime datefrom, DateTime dateto)
        {
            ViewBag.PageOf = 1;
            return PartialView("_ApprovalList", PermissionRepo.DateSearchApp(datefrom, dateto));
        }

        public ActionResult Approve(long id)
        {
            return PartialView("_Approve", PermissionRepo.ById(id));
        }
        [HttpPost]
        public ActionResult Approve(PermissionView model)
        {
            ResponseResult result = PermissionRepo.Approve(model, model.id);
            return Json(
                new
                {
                    success = result.Success,
                    message = result.Message
                },
                JsonRequestBehavior.AllowGet);
        }

        public ActionResult Reject(long id)
        {
            return PartialView("_Reject", PermissionRepo.ById(id));
        }

        [HttpPost]
        public ActionResult Reject(PermissionView model)
        {
            ResponseResult result = PermissionRepo.Reject(model, model.id);
            return Json(
                new
                {
                    success = result.Success,
                    message = result.Message
                },
                JsonRequestBehavior.AllowGet);
        }

        //Get
        public ActionResult Create()
        {
            return PartialView("_Create");
        }

        [HttpPost]
        public ActionResult Create(PermissionView model)
        {
            ResponseResult result = PermissionRepo.Update(model);
            return Json(
                new
                {
                    success = result.Success,
                    message = result.Message,
                    entity = result.Entity
                },
                JsonRequestBehavior.AllowGet);
        }

        public ActionResult Detail(long id)
        {
            return PartialView("_Detail", PermissionRepo.ById(id));
        }
    }
}

WFH-240/Controllers/ReligionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WFHDataModel;
using WFHRepository;

namespace WFH_240.Controllers
{
    public class ReligionController : Controller
    {
        // GET: Religion
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult List(int page = 1, string search = "", bool sortAsc = true, int perPage = 10)
        {
            Pagination pg = ReligionRepo.Paging(page, search, sortAsc, perPage);
            ViewBag.currPage = page;
            ViewBag.PageCount = pg.Pages;
            return PartialView("_List", pg.ListOf);
        }

        //Get
        public ActionResult Create()
        {
            return PartialView("_Create");
        }

        [HttpPost]
        public ActionResult Create(x_religion model)
        {
            ResponseResult result = ReligionRepo.Update(model);
            return Json(
                new
                {
                    success = result.Success,
                    message = result.Message,
                    entity = result.Entity
                },
                JsonRequestBehavior.AllowGet);
        }

        //Get
        public ActionResult Edit(long id)
        {
            return PartialView("_Edit", ReligionRepo.ById(id));
        }

        [HttpPost]
        public ActionResult Edit(x_religion model)
        {
            ResponseResult result = ReligionRepo.Update(model);
            return Json(
                new
                {
                    success = result.Success,
                    message = result.Message
                },
                JsonRequestBehavior.AllowGet);
        }

        //Get
        public ActionResult Delete(long id)
        {
            return PartialView("_Delete", ReligionRepo.ById(id));
        }

        [HttpPost]
        public ActionResult Delete(x_religion model)
        {
            ResponseResult result = ReligionRepo.Delete(model.id);
            return Json(
                new
                {
                    success = result.Success,
                    message = result.Message
                },
                JsonRequestBehavior.AllowGet);

        }

    }
}

WFH-240/Controllers/ResourceProjectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WFHDataModel;
using WFHRepository;
using WFHViewModel;

namespace WFH_240.Controllers
{
    public class ResourceProjectController : Controller
    {
        // GET: ResourceProject
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult List(int page = 1, string search = "", bool sortAsc = true, int perPage = 10)
        {
            Pagination pg = ResourceProjectRepo.Paging(page, search, sortAsc, perPage);
            ViewBag.currPage = page;
            ViewBag.PageCount = pg.Pages;
            return PartialView("_List", pg.ListOf);
        }

        public ActionResult SearchDate(DateTime datefrom, DateTime dateto)
        {
            ViewBag.PageOf = 1;
            return PartialView("_List", ResourceProjectRepo.SearchDate(datefrom, dateto));
        }

        public ActionResult SearchBoth(DateTime datefrom, DateTime dateto, string search)
        {
            ViewBag.PageOf = 1;
            return PartialView("_List", ResourceProjectRepo.SearchBoth(datefrom, dateto, search));
        }

        public ActionResult Create()
        {
            ViewBag.ClientList = new SelectList(ClientRepo.All(), "id", "name");
            return PartialView("_Create");
        }

        [HttpPost]
        public ActionResult Create (ResourceProView model) 
        {
            ResponseResult result = ResourceProjectRepo.Create(model);
            return Json(
                new
                {
                    success = result.Success,
                    message = result.Message,
                    entity = result.Entity
                },
                JsonRequestBehavior.AllowGet);
        }

        public ActionResult Detail(long id)
        {
            return PartialView("_Detail", ResourceProjectRepo.ById(id));
        }

        //Get
        public ActionResult Edit(long id)
        {
            ViewBag.ClientList = new SelectList(ClientRepo.All(), "id", "name");
            return PartialView("_Edit", ResourceProjectRepo.ById(id));
        }

        [HttpPost]
        public ActionResult Edit(ResourceProView model)
        {
            ResponseResult result = ResourceProjectRepo.Edit(model);
            return Json(
                new
                {
                    success = result.Success,
                    message = result.Message,
                    entity = result.Entity
                },
                JsonRequestBehavior.AllowGet);
        }

        //Get
        public ActionResult Delete(long id)
        {
            return PartialView("_Delete", ResourceProjectRepo.ById(id));
        }

        [HttpPost]
        public ActionResult Delete(ResourceProView model)
        {
            ResponseResult result = ResourceProjectRepo.Delete(model.id);
            return Json(
                new
                {
                    success = result.Success,
                    message = result.Message
                },
                JsonRequestBehavior.AllowGet);

        }
    }
}

WFH-240/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div id="nav" class="navbar navbar-inverse navbar-fixed-top" style="background-color:#121e79; color: white">
        <div class="container">
            <div class="navbar-header">
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a style="color:white" href="@Url.Action("Index", "Home")"><b>Home</b></a></li>
                        <li><a style="color:white" href="@Url.Action("About", "Home")"><b>About</b></a></li>
                        <li><a style="color:white" href="@Url.Action("Contact", "Home")"><b>Contact</b></a></li>
                        <li class="dropdown notifications-menu" style="float:left">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" style="color:white">
                                <span class="logo-lg-action"> <strong>Menu 1</strong></span>
                                <i class="glyphicon glyphicon-chevron-down"></i>
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                <li><a class="dropdown-item" href="#">List 1</a></li>
                                <li><a class="dropdown-item" href="#">List 2</a></li>
                            </ul>
                        </li>
                        <li><a style="color:white" href="@Url.Action("Index", "Religion")"><b>Religion</b></a></li>
                        <li><a style="color:white" href="@Url.Action("Index", "Permission")"><b>Permission</b></a></li>
                        <li><a style="color:white" href="@Url.Action("Index", "ResourceProject")">
                            <b>Resource Project</b></a></li>
                    </ul>
                    <ul class="nav navbar-nav text-right" style="float:right; margin-right: 50px">
                        <li class="dropdown notifications-menu">
                            <a href="#" class="dropdown-toggle" style="color:#ffffff" data-toggle="dropdown">
                                <i class="glyphicon glyphicon-bell"></i>
                                <span class="logo-lg"><b>Hi, Inas</b></span>
                                <i class="glyphicon glyphicon-chevron-down"></i>
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                <li><a class="dropdown-item" href="#">Ubah Kata Sandi</a></li>
                                <li><a class="dropdown-item" href="#">Logout</a></li>
                            </ul>
                        </li>
                    </ul>

                </div>
            </div>
        </div>
    </div>

    <div class="container body-content" style="background:lightgrey">
        @RenderBody()
        <hr />
    </div>
    <footer class="col-md-offset-1">
        <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

<!--
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { at class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <!-- Judul, namaview, namafolder
                <li>Html.ActionLink("Home", "Index", "Home")</li>
                <li>Html.ActionLink("About", "About", "Home")</li>
                <li>Html.ActionLink("Contact", "Contact", "Home")</li>
                <li>Html.ActionLink("Religion", "Index", "Religion")</li>
                <li>Html.ActionLink("Permission", "Index", "Permission")</li>
                <li>Html.ActionLink("Resource Project", "Index", "ResourceProject")</li>
            </ul>
        </div>
    </div>
</div> -->